### ISSUE TITLE
Make Python 3 compatible

### ISSUE THREAD

**Issue by amyrlam** [fastly/fastly-py#17]
[  ] Check out 2to3 https://docs.python.org/2/library/2to3.html
[  ] Take over https://github.com/zebrafishlabs/fastly-python and combine? @zebrafishlabs

**Comment by joshblum** [comment]
@amyrlam Any update on this? Is this library still maintained? Would be happy to contribute if that's helpful.

**Comment by amyrlam** [comment]
@trcarden @joshblum Hey, sorry this has been open for so long! I was hoping we could move forward with https://github.com/fastly/fastly-py/pull/31, but it looks like we will need to still support Python 2 from the download stats. 

Hope to have more info from the Fastly side soon re: this repo.

**Comment by psbanka** [comment]
Fixed with v0.2.3
