### ISSUE TITLE
Documentation: describe the entire process of setting up a fastly service and using it to test this library

### ISSUE THREAD

**Issue by psbanka** [fastly/fastly-py#54]
Currently it's necessary to set up an `.env` file and `source` it before testing. This file requires a lot of information about a fastly user account (including username, password, account token, service-id. Plus the service-id that you reference needs to have certain things set up, but none of this configuration is documented. Let's get this fully documented so it's easy for anyone to test this library.

**Comment by hannesvz** [comment]
Not only is that undocumented, I can't find any documentation for anything in this module. Are there any docs for it, or are we supposed to simply figure out which class does what based on the raw Fastly API docs?

**Comment by Integralist** [comment]
Closing this issue now we've published v1.0.0 https://pypi.org/project/fastly/
