### ISSUE TITLE
Contribution guide

### ISSUE THREAD

**Issue by psbanka** [fastly/fastly-py#57]
It'd be nice for potential new contributors to be able to know how we do business. Probably should include a code-of-conduct, requirements for PRs (for example, new PRs should have tests and should include updates to the CLI).

**Comment by psbanka** [comment]
Also maybe add a section on how maintainers will respond to PRs and maybe some goals as to how quickly we will respond to PRs.

**Comment by psbanka** [comment]
include instructions for forking and submitting PRs.

**Comment by Integralist** [comment]
Closing this issue now we've published v1.0.0 https://pypi.org/project/fastly/
