### ISSUE TITLE
Support for TLS Subscriptions

### ISSUE THREAD

**Issue by matejsvirk** [fastly/fastly-py#65]
One of the features that are currently not implemented in the fastly-py is a model for TLS subscriptions. 
This came up when one of our prospects tried to automate their domain/TLS deployment flow using python. 
He worked around it with Requests library and our API endpoints which did the job, but an _official_ support would be great. 

Thanks!

**Comment by Integralist** [comment]
Closing this issue now we've published v1.0.0 https://pypi.org/project/fastly/
