### ISSUE TITLE
No proxy support

### ISSUE THREAD

**Issue by mzpqnxow** [fastly/fastly-py#77]
It appears that because the underlying HTTP is powered by the minimal most low-level Python HTTP package that there's no easy way to use a proxy. I'm not sure if this project is still maintained or if it's just an "as-is" alternative to the more up-to-date golang CLI

It would make much more sense to use the third-party `requests` package which is the standard for nearly all Python projects doing anything but the simplest HTTP operations

Rather than hack in proxy support, I'm going to fork `fastly-py` and make the necessary changes to make it work with `requests`, if you're interest in a PR I'm happy to submit it but it will be a pretty invasive change

**Comment by Integralist** [comment]
Thanks @mzpqnxow for opening this issue.

For future travellers I'll cross-link to my comments in your PR related to the future plans for `fastly-py` (the summary being: a newly rewritten version is planned).

https://github.com/fastly/fastly-py/pull/78#issuecomment-899425985

**Comment by mzpqnxow** [comment]
Closing this, it has served its purpose

Thanks!
