### ISSUE TITLE
Repo abandoned?

### ISSUE THREAD

**Issue by colbygk** [fastly/fastly-py#79]
Is this repo abandoned? There are several PR's going back to 2020 that have no movement. Our own project still requires a working 2.7 compatible fastly library (for now) and we need to be able to access ACLs. I have a fork where I am adding this ability and about to submit a PR, but it looks like that may be in vain.

**Comment by Integralist** [comment]
Hi @colbygk thanks for raising this issue.

To clarify, we are aware that there are a bunch of neglected API clients. 

The only API client which has seen regular updates has been the [Go client](https://github.com/fastly/go-fastly).

The Fastly Developer Relations team have begun working on a new set of 'code generated' API clients, and we are slowly iterating and improving the quality of the generated code. 

We have already begun rolling out _pre-releases_ for the following _initial_ set of languages...

- A beta [JS client](https://github.com/fastly/fastly-js/releases/tag/3.0.0-beta1).
- A beta [PHP client](https://github.com/fastly/fastly-php/releases/tag/v1.0.0-beta2).
- An alpha [Ruby client](https://github.com/fastly/fastly-ruby/releases/tag/v4.0.0.alpha2).

I can't give an exact time frame, but I believe the Python client is next on our list.

Hope this helps clarify the situation with the current set of API clients.

**Comment by Integralist** [comment]
Quick update:
- https://pypi.org/project/fastly/1.0.0a1/
- https://github.com/fastly/fastly-py/tree/1.0.0.alpha1

**Comment by Integralist** [comment]
Looks like I was mistaken, and we're actually on alpha 2...

- https://pypi.org/project/fastly/1.0.0a2/
- https://github.com/fastly/fastly-py/tree/1.0.0.alpha2

**Comment by alex-vogibyte** [comment]
Hello, Any progress with beta or ETA of the first release?

**Comment by Integralist** [comment]
Hi @alex-vogibyte 

There have been no further updates to the alpha release client `1.0.0.alpha2` (https://pypi.org/project/fastly/#history) but I'll check in with the team to see what feedback we've received so far with the Python client (as some customers have been using it for testing and giving early feedback).

**Comment by Integralist** [comment]
**Quick update**: we have work scheduled in the next quarter to get our alpha code generated API clients moved to an official 1.x release.

**Comment by Integralist** [comment]
Closing this issue now we've published v1.0.0 https://pypi.org/project/fastly/

**Comment by chingc** [comment]
@Integralist Are there any breaking changes people should be aware of when upgrading to v1.0?  I noticed there is no update to the CHANGELOG and when I took a look at the v1 commit it's a massive change: `Showing 1,438 changed files with 301,720 additions and 1,268 deletions.`

**Comment by Integralist** [comment]
Hi @chingc 

Apologies for the confusion.

I intended to publish a change log but a last-minute priority prevented me (and then I was out on PTO until today). I'll be sure to get one written up ASAP, and I'll ping back to this thread once it's done.

Thanks.

**Comment by Integralist** [comment]
Hi @chingc  

Thanks for your patience.

I've added a new entry to the [CHANGELOG.md](https://github.com/fastly/fastly-py/blob/main/CHANGELOG.md) with links to what is hopefully useful information regarding the new v1 release.
