### ISSUE TITLE
List services endpoint?

### ISSUE THREAD

**Issue by joestump** [fastly/fastly-py#8]
Looks like this isn't supported? The API documents are ambiguous on if you can even get a list of services, but it seems possible?

http://docs.fastly.com/docs/api#service

**Comment by lisac** [comment]
I've taken a stab at this in PR #29 .

**Comment by dcmoore-gd** [comment]
@joestump Now that @psbanka has merged #30 (which included functionality in @lisac's #29) your request should be addressed in and I think this issue can be closed.

**Comment by agassner** [comment]
API.services() call is not in pypi, any issue with the release?
The code is there https://github.com/fastly/fastly-py/blob/master/fastly/fastly.py#L28-L29
